export class RepositoryConsts {

  public static DATABASE_CONNECTION_SMART_NOTIFY: string =
    'DATABASE_CONNECTION_SMART_NOTIFY';


  public static SMART_NOTIFY_NOTIFY_HISTORY_REPOSITORY: string = 'SMART_NOTIFY_NOTIFY_HISTORY_REPOSITORY';
}
